cliente:
    path:     /
    defaults: { _controller: "ImaginativoTSBundle:Cliente:index" }

cliente_show:
    path:     /{id}/show
    defaults: { _controller: "ImaginativoTSBundle:Cliente:show" }

cliente_new:
    path:     /new
    defaults: { _controller: "ImaginativoTSBundle:Cliente:new" }

cliente_create:
    path:     /create
    defaults: { _controller: "ImaginativoTSBundle:Cliente:create" }
    requirements: { _method: post }

cliente_edit:
    path:     /{id}/edit
    defaults: { _controller: "ImaginativoTSBundle:Cliente:edit" }

cliente_update:
    path:     /{id}/update
    defaults: { _controller: "ImaginativoTSBundle:Cliente:update" }
    requirements: { _method: post|put }

cliente_delete:
    path:     /{id}/delete
    defaults: { _controller: "ImaginativoTSBundle:Cliente:delete" }
    requirements: { _method: post|delete }
