membro:
    path:     /
    defaults: { _controller: "ImaginativoTSBundle:Membro:index" }

membro_show:
    path:     /{id}/show
    defaults: { _controller: "ImaginativoTSBundle:Membro:show" }

membro_new:
    path:     /new
    defaults: { _controller: "ImaginativoTSBundle:Membro:new" }
    
membro_equipe_new:
    path:     /{id}/membroequipe
    defaults: { _controller: "ImaginativoTSBundle:Membro:newMembroEquipe" }

membro_create:
    path:     /create
    defaults: { _controller: "ImaginativoTSBundle:Membro:create" }
    requirements: { _method: post }
    
membro_equipe_create:
    path:     /{id}/create
    defaults: { _controller: "ImaginativoTSBundle:Membro:createMembroEquipe" }
    requirements: { _method: post|put }    

membro_edit:
    path:     /{id}/edit
    defaults: { _controller: "ImaginativoTSBundle:Membro:edit" }

membro_update:
    path:     /{id}/update
    defaults: { _controller: "ImaginativoTSBundle:Membro:update" }
    requirements: { _method: post|put }

membro_delete:
    path:     /{id}/delete
    defaults: { _controller: "ImaginativoTSBundle:Membro:delete" }
    requirements: { _method: post|delete }
